name: MinigameManager
main: com.comdude2.minigame.managers.MinigameManager
version: 1.0
author: comdude2, daawsomest
commands:
   mm:
      description: This is the main command for MinigameManager.
      usage: /<command> [sub-command]
      aliases: [minigame]
      permission: mm.use
      permission-message: You don't have permission to do this!